workspace(name = "hyw_sim")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Hedron compile_commands for clangd / IDE (same as grading_mini)
http_archive(
    name = "hedron_compile_commands",
    strip_prefix = "bazel-compile-commands-extractor-0e990032f3c5a866e72615cf67e5ce22186dcb97",
    urls = ["https://github.com/hedronvision/bazel-compile-commands-extractor/archive/0e990032f3c5a866e72615cf67e5ce22186dcb97.tar.gz"],
)
load("@hedron_compile_commands//:workspace_setup.bzl", "hedron_compile_commands_setup")
hedron_compile_commands_setup()
load("@hedron_compile_commands//:workspace_setup_transitive.bzl", "hedron_compile_commands_setup_transitive")
hedron_compile_commands_setup_transitive()
load("@hedron_compile_commands//:workspace_setup_transitive_transitive.bzl", "hedron_compile_commands_setup_transitive_transitive")
hedron_compile_commands_setup_transitive_transitive()
load("@hedron_compile_commands//:workspace_setup_transitive_transitive_transitive.bzl", "hedron_compile_commands_setup_transitive_transitive_transitive")
hedron_compile_commands_setup_transitive_transitive_transitive()

http_archive(
    name = "rules_cc",
    strip_prefix = "rules_cc-0.0.9",
    urls = ["https://github.com/bazelbuild/rules_cc/releases/download/0.0.9/rules_cc-0.0.9.tar.gz"],
)

http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-25.3",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/refs/tags/v25.3.tar.gz"],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()

# ---- spdlog (sim_runner file log; same stack as grading_mini) ----
http_archive(
    name = "com_github_gabime_spdlog",
    build_file = "//third_party:spdlog.BUILD",
    strip_prefix = "spdlog-1.13.0",
    urls = ["https://github.com/gabime/spdlog/archive/refs/tags/v1.13.0.tar.gz"],
)

http_archive(
    name = "com_github_fmtlib_fmt",
    build_file = "//third_party:fmt.BUILD",
    strip_prefix = "fmt-10.2.1",
    urls = ["https://github.com/fmtlib/fmt/archive/refs/tags/10.2.1.tar.gz"],
)

# Hedron's Compile Commands Extractor for Bazel
# 建议去 GitHub 仓库获取最新的 commit hash 以替换下面的 URL 和 strip_prefix
http_archive(
    name = "hedron_compile_commands",
    url = "https://github.com/hedronvision/bazel-compile-commands-extractor/archive/1e08f8e0507b6b6b1f4416a9a22cf5c28beaba93.tar.gz",
    strip_prefix = "bazel-compile-commands-extractor-1e08f8e0507b6b6b1f4416a9a22cf5c28beaba93",
)

# 记载并运行工作区设置
load("@hedron_compile_commands//:workspace_setup.bzl", "hedron_compile_commands_setup")
hedron_compile_commands_setup()
local_repository(
    name = "grading_mini",
    path = "../grading_mini",
)